### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by benadamstyles** [jaredly/myntax#1]
Hey! Thanks for making a start on the decorators syntax 🙂

I really like the lisp syntax and I'd love to help push it forward. One of the main pain points for me currently is the documentation – and I'd like to help out if I can. Would you accept a PR? And how/where do you think it best to put it? I'm basically just thinking of a complement to `LispGrammar.md` that has examples of how to write out each basic construct.

**Comment by jaredly** [comment]
Yeah, that would be awesome! Maybe make a `docs/LispQuickstart.md` or something?
