### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by benadamstyles** [jaredly/myntax#5]
Hey, sorry to keep bombarding you – please don't feel any pressure to respond immediately.

I'm getting weird formatting from the lisp refmt that seems to be caused by the new `@bs.module` or `external` syntax. This is how one file was reformatted:

```clj
(@bs.module
"../constants/styles/typography"
(external

fontSizes
(Js.Dict.t int)
""))

(defn resolveFontSize [key]
  (switch (Js.Dict.get
    fontSizes
    key)
    None 14.0
    (Some f)
      (float_of_int f)))
```

**Comment by jaredly** [comment]
Oh good call :) yeah I didn't define indentation rules for that

**Comment by jaredly** [comment]
here's how that works
https://github.com/jaredly/myntax/commit/c05c62174f3ecd6d1c11088def0df8db3d38798d
